# Step 4 Topic Modeling Results Analysis

In [12]:
import pandas as pd
from bertopic import BERTopic

## 1 Read in Data, Model and Topics
### 1.1 Load Topic Model

In [7]:
topic_model = BERTopic.load("results/model_tfidf_model")

In [9]:
#get the topics frequencies
freq = topic_model.get_topic_info()
freq

,Topic,Count,Name,Representation,Representative_Docs
0,-1,923,-1_development_planning_building_process,"[development, planning, building, process, pol...",[decision maker facing unprecedented challenge...
1,0,453,0_gis_land_ca_growth,"[gis, land, ca, growth, automaton, cellular, p...",[zone cell parcel long regarded main unit anal...
2,1,151,1_accessibility_travel_cycling_commuting,"[accessibility, travel, cycling, commuting, bi...",[people value enjoy benefit use car brings qua...
3,2,81,2_design_style_designer_architectural,"[design, style, designer, architectural, archi...",[two experiment reported examine hypothesis co...
4,3,76,3_network_centrality_street_topology,"[network, centrality, street, topology, traffi...",[transportation research ha usually seen road ...
5,4,52,4_homeless_social_tourist_mobile,"[homeless, social, tourist, mobile, mobility, ...",[mobile internet emerges numerous instagram wo...
6,5,49,5_rectangular_adjacency_room_dissection,"[rectangular, adjacency, room, dissection, max...",[procedure described generates dissection rect...
7,6,49,6_facility_heuristic_problem_solution,"[facility, heuristic, problem, solution, cover...",[previous research effort demonstrate use loca...
8,7,48,7_energy_heat_temperature_canopy,"[energy, heat, temperature, canopy, carbon, tr...",[local climate change due urbanization epitomi...
9,8,47,8_segregation_ethnic_tract_residential,"[segregation, ethnic, tract, residential, gend...",[segregation highly nuanced concept researcher...
10,9,44,9_visibility_isovist_museum_visible,"[visibility, isovist, museum, visible, isovist...",[space seen vantage point called isovist set s...
11,10,41,10_shopping_retail_internet_store,"[shopping, retail, internet, store, retailer, ...",[paper implication examined retail planning us...
12,11,39,11_disaster_flood_hazard_recovery,"[disaster, flood, hazard, recovery, resilience...",[given japan substantial exposure many kind na...
13,12,37,12_pedestrian_walking_walkability_crosswalk,"[pedestrian, walking, walkability, crosswalk, ...",[dynamic vision refers person visual perceptio...
14,13,35,13_shape_grammar_schema_interpreter,"[shape, grammar, schema, interpreter, algebra,...",[need implement shape grammar efficiently rath...
15,14,29,14_architect_regulation_control_deregulation,"[architect, regulation, control, deregulation,...",[victorian government introduced better apartm...
16,15,27,15_covid_pandemic_epidemic_disease,"[covid, pandemic, epidemic, disease, dashboard...",[new york city nyc wa epicenter covid pandemic...
17,16,25,16_fractal_dimension_vista_multifractal,"[fractal, dimension, vista, multifractal, mult...",[paper compare built pattern urban form south ...
18,17,24,17_grammar_ambiguity_shape_parametric,"[grammar, ambiguity, shape, parametric, house,...",[paper explores application informal shape gra...
19,18,23,18_nondomestic_stock_energy_building,"[nondomestic, stock, energy, building, floor, ...",[article describes development new three dimen...
20,19,23,19_crime_alcohol_outlet_fear,"[crime, alcohol, outlet, fear, violence, offen...",[statistical analysis urban environment recent...
21,20,20,20_galois_lattice_judgment_discrimination,"[galois, lattice, judgment, discrimination, mu...",[multiattribute evaluation method used without...
22,21,20,21_participation_cab_participatory_citizen,"[participation, cab, participatory, citizen, a...",[despite planning support system ps becoming i...
23,22,19,22_scenic_landscape_beauty_preference,"[scenic, landscape, beauty, preference, trail,...",[timber harvesting operation especially clearc...
24,23,19,23_water_groundwater_runoff_stormwater,"[water, groundwater, runoff, stormwater, deslu...",[study addressing outdoor water use residentia...
25,24,18,24_house_vernacular_genotype_archaeology,"[house, vernacular, genotype, archaeology, pre...",[prehistoric cultural landscape chaco canyon m...
26,25,17,25_pwd_osm_border_mapmakers,"[pwd, osm, border, mapmakers, voting, symbol, ...",[paper investigates applicability knowledge do...
27,26,16,26_sound_noise_complaint_odour,"[sound, noise, complaint, odour, acoustic, sou...",[study focused multisensory perception audio o...
28,27,16,27_smart_ict_governance_digital,"[smart, ict, governance, digital, mission, con...",[information communication technology ict wide...
29,28,15,28_pm_air_pollution_emission,"[pm, air, pollution, emission, pollutant, ozon...",[air quality affected interplay emission sourc...
30,29,15,29_negotiation_stakeholder_game_landowner,"[negotiation, stakeholder, game, landowner, de...",[quality urban living environment strongly rel...
31,30,14,30_virtual_vr_reality_covisibility,"[virtual, vr, reality, covisibility, environme...",[existing online virtual world electronic envi...
32,31,14,31_design_cgi_designer_generative,"[design, cgi, designer, generative, optimizati...",[study proposes prototype smart rendering urba...
33,32,14,32_russian_eastern_russia_soviet,"[russian, eastern, russia, soviet, fund, forme...",[environmental action programme central easter...
34,33,13,33_regret_scheduling_choice_wtp,"[regret, scheduling, choice, wtp, habitual, mi...",[study show coexistence different decision rul...
35,34,13,34_expert_knowledge_kb_cbr,"[expert, knowledge, kb, cbr, ps, modelobjects,...",[high complexity uncertainty subjectivity urba...
36,35,13,35_overrun_cost_cba_project,"[overrun, cost, cba, project, dap, lock, infra...",[lock escalating commitment decision maker ine...
37,36,12,36_discourse_toulmin_argument_clock,"[discourse, toulmin, argument, clock, speculat...",[planning public policy endeavour argumentativ...
38,37,11,37_dissipative_bifurcation_catastrophe_bank,"[dissipative, bifurcation, catastrophe, bank, ...",[theory dissipative structure ha used year mai...
39,38,11,38_imagery_sidewalk_image_learning,"[imagery, sidewalk, image, learning, trained, ...",[although reliable accurate inventorying sidew...

In [10]:
# Get all word representing each topic from topic model
from src.analysistools import __get_topic_allwords__
topic_allwords = __get_topic_allwords__(freq.Topic, topic_model)
topic_allwords

      Topic  Freq                                              Words
0   Topic-1   923  [development, planning, building, process, pol...
1    Topic0   453  [gis, land, ca, growth, automaton, cellular, p...
2    Topic1   151  [accessibility, travel, cycling, commuting, bi...
3    Topic2    81  [design, style, designer, architectural, archi...
4    Topic3    76  [network, centrality, street, topology, traffi...
5    Topic4    52  [homeless, social, tourist, mobile, mobility, ...
6    Topic5    49  [rectangular, adjacency, room, dissection, max...
7    Topic6    49  [facility, heuristic, problem, solution, cover...
8    Topic7    48  [energy, heat, temperature, canopy, carbon, tr...
9    Topic8    47  [segregation, ethnic, tract, residential, gend...
10   Topic9    44  [visibility, isovist, museum, visible, isovist...
11  Topic10    41  [shopping, retail, internet, store, retailer, ...
12  Topic11    39  [disaster, flood, hazard, recovery, resilience...
13  Topic12    37  [pedestrian, walking, walkability, crosswalk, ...
14  Topic13    35  [shape, grammar, schema, interpreter, algebra,...
15  Topic14    29  [architect, regulation, control, deregulation,...
16  Topic15    27  [covid, pandemic, epidemic, disease, dashboard...
17  Topic16    25  [fractal, dimension, vista, multifractal, mult...
18  Topic17    24  [grammar, ambiguity, shape, parametric, house,...
19  Topic18    23  [nondomestic, stock, energy, building, floor, ...
20  Topic19    23  [crime, alcohol, outlet, fear, violence, offen...
21  Topic20    20  [galois, lattice, judgment, discrimination, mu...
22  Topic21    20  [participation, cab, participatory, citizen, a...
23  Topic22    19  [scenic, landscape, beauty, preference, trail,...
24  Topic23    19  [water, groundwater, runoff, stormwater, deslu...
25  Topic24    18  [house, vernacular, genotype, archaeology, pre...
26  Topic25    17  [pwd, osm, border, mapmakers, voting, symbol, ...
27  Topic26    16  [sound, noise, complaint, odour, acoustic, sou...
28  Topic27    16  [smart, ict, governance, digital, mission, con...
29  Topic28    15  [pm, air, pollution, emission, pollutant, ozon...
30  Topic29    15  [negotiation, stakeholder, game, landowner, de...
31  Topic30    14  [virtual, vr, reality, covisibility, environme...
32  Topic31    14  [design, cgi, designer, generative, optimizati...
33  Topic32    14  [russian, eastern, russia, soviet, fund, forme...
34  Topic33    13  [regret, scheduling, choice, wtp, habitual, mi...
35  Topic34    13  [expert, knowledge, kb, cbr, ps, modelobjects,...
36  Topic35    13  [overrun, cost, cba, project, dap, lock, infra...
37  Topic36    12  [discourse, toulmin, argument, clock, speculat...
38  Topic37    11  [dissipative, bifurcation, catastrophe, bank, ...
39  Topic38    11  [imagery, sidewalk, image, learning, trained, ...

### 1.2 Load Topic Overtime dataframe

In [11]:
topics_over_time = pd.read_csv("results/topics_over_time_tfidf_model.csv").iloc[:,1:]
topics_over_time.head()

,Topic,Words,Frequency,Timestamp,Name
0,-1,"algebraic, simplicial, exterior, averaging, ma...",6,1974,-1_development_planning_building_process
1,2,"wright, froebel, sullivan, kind, office",2,1974,2_design_style_designer_architectural
2,6,"teaching, timetabling, minimum, demand, utilis...",1,1974,6_facility_heuristic_problem_solution
3,14,"regulation, bonus, sydney, floor, return",1,1974,14_architect_regulation_control_deregula...
4,18,"heating, appliance, heat, costing, conservation",1,1974,18_nondomestic_stock_energy_building

### 1.3 Load Abstract Data

In [ ]:
###################
# Part 2 Stack Bars
###################
import matplotlib.pyplot as plt

# * Step1: Get the dataframe for the visualization
def GetTopicCountByYear(topiclist, evo_table, yearlycount):
    # extract the key info from eveolution table
    temp_df = evo_table.loc[:, ['Topic', 'Frequency', 'Timestamp']]
    # print(temp_df)

    # Loop through the keywords list to draw lins on Cavas
    topiclist.sort()
    # print("TopicList", topiclist)
    legend_list = []

    # Create a dataframe to hold the all topics, freq, year amount
    stack_df = pd.DataFrame()

    for item in range(0, len(topiclist)):
        topic = topiclist[item]
        topic_label = "Topic " + str(topic)
        # print("Topic", topic)
        legend_list.append("Topic" + str(topic))

        # Extract visulize dataframe
        visual_df = temp_df[temp_df.Topic == topic].reset_index(drop=True)
        visual_df = visual_df.rename(columns={'Timestamp': 'Publication Year'})  # rename timstamp to year fro merge
        #print(visual_df.head())
        #print(yearcount.head())
        # Merge on year
        final_visual_df = pd.merge(visual_df, yearlycount, on="Publication Year")
        # print(final_visual_df.head())
        #stack_df = stack_df.append(final_visual_df)
        stack_df = pd.concat([stack_df, final_visual_df])

    # group the df based on year and topics
    #grouped_stack = stack_df.groupby(["year", "Topic"])["Frequency"].sum().reset_index()
    grouped_stack = stack_df.groupby(["Publication Year", "Topic"])["Frequency"].sum().reset_index()
    # pivot the dataframe into the correct format
    grouped_stack_df = grouped_stack.pivot(index='Publication Year', columns='Topic', values='Frequency').fillna(0).reset_index()
    # print(grouped_stack_df.head())

    return grouped_stack_df


# * Step2: Satcked bar visualization
# Get the topic evo for each topic
def GetTopicEvo(topiclist, overtime):  # topics list, topic_model, topic over time dataframe
    finaldataframe = pd.DataFrame()
    for topic in topiclist:
        # print(topic)
        tempdf = overtime[overtime.Topic == topic].reset_index(drop=True)
        # print(tempdf.head())
        # finaldataframe = finaldataframe.append(tempdf)
        finaldataframe = pd.concat([finaldataframe, tempdf])
    return finaldataframe


def VisualizeStackByYearColor(data, year_range, PlotTitle):  # 3String
    plt.style.use('default')

    # create the figure
    fig, ax = plt.subplots(figsize=(25, 10))
    # plt.figure(figsize=(25,10))
    plt.xlabel('Year', fontsize=30, fontname="Arial")
    plt.ylabel('Frequency', fontsize=30, fontname="Arial")

    print(len(data.columns[1:]))
    if len(data.columns[1:]) == 2:
        color_list = ['#4E62AB', '#FDB96A']

    if len(data.columns[1:]) == 3:
        color_list = ['#4E62AB', '#FDB96A', '#D6404E']

    if len(data.columns[1:]) == 4:
        color_list = ['#4E62AB', '#87CFA4', '#FDB96A', '#D6404E']

    if len(data.columns[1:]) == 5:
        color_list = ['#4E62AB', '#87CFA4', '#F5FBB1', '#FDB96A', '#D6404E']

    if len(data.columns[1:]) == 6:
        color_list = ['#4E62AB', '#87CFA4', '#CBE99D', '#FEE89A', '#F57547', '#9E0142']

    if len(data.columns[1:]) == 7:
        color_list = ['#4E62AB', '#469EB4', '#87CFA4', '#FEE89A', '#FDB96A', '#F57547', '#9E0142']

    if len(data.columns[1:]) == 8:
        color_list = ['#4E62AB', '#469EB4', '#87CFA4', '#F5FBB1', '#FEE89A', '#FDB96A', '#F57547', '#9E0142']

    if len(data.columns[1:]) == 9:
        color_list = ['#4E62AB', '#469EB4', '#87CFA4', '#F5FBB1', '#FEE89A', '#FDB96A', '#F57547', '#D6404E', '#9E0142']

    # Legend of the stacked bars
    bottom = 0
    colorid = 0
    legend_list = []
    for topic in data.columns[1:]:
        # legend
        topic_label = "Topic " + str(topic)
        # print("Topic", topic)
        legend_list.append("Topic" + str(topic))
        # bar plot
        # plt.bar(data.loc[:, 'year'], data[topic], bottom = bottom, width=0.95)
        plt.bar(data.index, data[topic], bottom=bottom, width=0.95, color=color_list[colorid])
        bottom = bottom + data[topic]
        colorid = colorid + 1

    # ax.set_title(PlotTitlem)
    plt.legend((legend_list), prop={'family': 'Arial', "size": 20}, loc='upper left', ncol=1)

    # set x ticks: dont' show the year without any topics
    #x_label = list(np.arange(data.year.min(), 2021, 5))
    #x_label.append(2021)
    #x_label = list(data.year)
    x_label = list(data["Publication Year"])
    print(x_label)

    x_ticks = []
    for year_index in range(0, len(x_label)):
        #print(year)
        year = x_label[year_index]
        try:
            temp = data[data['Publication Year'] == year].index[0]
            #print(temp)
        except:
            temp = data[data['Publication Year'] == year + 1].index[0]
        #if temp%5 == 0:
        x_ticks.append(temp)
    print(x_ticks)

    # x_ticks = data.index.to_list()
    # x_label = data.loc[:, 'year'].to_list()
    # x_label = np.arange(1975, 2021, 5)
    # Plot x and y axticks
    plt.gcf().autofmt_xdate()  # italics of x label
    plt.xticks(ticks=x_ticks, labels=x_label, fontsize=15)
    # plt.xticks(np.arange(1975, 2021, 5))
    plt.yticks(fontsize=25)
    plt.margins(x=0.01)
    plt.show()

def _visualsmall_(data, year_range):
    plt.style.use('default')

    print(len(data.columns[1:]))
    if len(data.columns[1:]) == 2:
        color_list = ['#4E62AB', '#FDB96A']

    if len(data.columns[1:]) == 3:
        color_list = ['#4E62AB', '#FDB96A', '#D6404E']

    if len(data.columns[1:]) == 4:
        color_list = ['#4E62AB', '#87CFA4', '#FDB96A', '#D6404E']

    if len(data.columns[1:]) == 5:
        color_list = ['#4E62AB', '#87CFA4', '#F5FBB1', '#FDB96A', '#D6404E']

    if len(data.columns[1:]) == 6:
        color_list = ['#4E62AB', '#87CFA4', '#CBE99D', '#FEE89A', '#F57547', '#9E0142']

    if len(data.columns[1:]) == 7:
        color_list = ['#4E62AB', '#469EB4', '#87CFA4', '#FEE89A', '#FDB96A', '#F57547', '#9E0142']

    if len(data.columns[1:]) == 8:
        color_list = ['#4E62AB', '#469EB4', '#87CFA4', '#F5FBB1', '#FEE89A', '#FDB96A', '#F57547', '#9E0142']

    if len(data.columns[1:]) == 9:
        color_list = ['#4E62AB', '#469EB4', '#87CFA4', '#F5FBB1', '#FEE89A', '#FDB96A', '#F57547', '#D6404E', '#9E0142']
    # ax = plt.axes()
    if year_range > 0:
        # figure and axis
        fig, ax = plt.subplots(1, figsize=(16, 9))
        plt.xlabel('Year', fontsize=20, fontname="Arial")

        print("Small plot is the topic before the year of ", year_range)
        #year_index = data[data['year'] == year_range].index[0]
        year_index = data[data['Publication Year'] == year_range].index[0]
        # print(year_index.tolist())
        small_df = data.iloc[:year_index, :]  # .set_index('year')
        # print(small_df.tail())

        bottom = 0
        colorid = 0
        for topic in data.columns[1:]:
            # bar plot
            # plt.bar(small_df.loc[:, 'year'], small_df[topic], bottom = bottom, width=0.95)
            plt.bar(small_df.index, small_df[topic], bottom=bottom, width=0.95, color=color_list[colorid])
            bottom = bottom + small_df[topic]
            colorid = colorid + 1

        # remove spines
        # ax.spines['right'].set_visible(False)
        # ax.spines['left'].set_visible(False)
        # ax.spines['top'].set_visible(False)
        # ax.spines['bottom'].set_visible(False)
        x_ticks = small_df.index
        #x_label = small_df.loc[:, 'year'].to_list()
        x_label = small_df.loc[:, 'Publication Year'].to_list()

        plt.gcf().autofmt_xdate()  # italics of x label
        plt.xticks(ticks=x_ticks, labels=x_label, fontsize=15)
        plt.yticks(fontsize=25)
        plt.margins(x=0.01)
        plt.show()


###############################END OF PART TWO#############################################